# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef6aa5033ff7fbb82db8181622095ea9fb1701632ccc8e924b6a0b1d1b2cb96fd790775badcb5edb3923d0f0d4c589c89d8a3572b75812f868b079ecb9bea3bc

test:
  secret_key_base: 39588fa67e521e3d0c67013959c267053ca60bdc1e58b4bfee12340f63f995ab21e03663c44a9ae7c85a7c7a45cbb01c21cd37927280b52fef57924171c49c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
